const express = require('express')
const router = express.Router()
const userType = require('./User')

router.post('/v1/login', userType.login)
router.post('/v1/register', userType.register)
router.get('/v1/logout', userType.logout)
router.get('/v1/token/state', userType.getTokenState)
router.get('/v1/sms', userType.getVerificationCode)
router.post('/v1/user/info/complete', userType.completeUserInfo)
router.post('/v1/user/info', userType.getUserInfo)
router.post('/v1/user/center', userType.getUserCenterData)
router.get('/v1/user/friend', userType.getUserFriendShip)
router.post('/v1/user/friend/detail', userType.getUserFriendShipDetail)
router.post('/v1/user/info/get', userType.getUserInfoByUpdate)
router.post('/v1/user/info/update', userType.updateUserInfo)
router.get('/v1/user/message', userType.getUserMessage)
module.exports = router